import { StoreData } from '@type/popUp';

export const storeDataDummy: StoreData[] = [
  {
    id: 1,
    thumbnail: 'https://placehold.co/600x400/png',
    cityName: '도시명',
    neighborhoodName: '동네명',
    name: '팝업스토어 제목',
    area: 0,
    numOfPeople: 0,
    date: 1,
    price: 100000,
    isLiked: false,
  },
  {
    id: 2,
    thumbnail: 'https://placehold.co/600x400/png',
    cityName: '도시명',
    neighborhoodName: '동네명',
    name: '팝업스토어 제목',
    area: 0,
    numOfPeople: 0,
    date: 2,
    price: 100000,
    isLiked: false,
  },
  {
    id: 3,
    thumbnail: 'https://placehold.co/600x400/png',
    cityName: '도시명',
    neighborhoodName: '동네명',
    name: '팝업스토어 제목',
    area: 0,
    numOfPeople: 0,
    date: 3,
    price: 100000,
    isLiked: false,
  },
  {
    id: 4,
    thumbnail: 'https://placehold.co/600x400/png',
    cityName: '도시명',
    neighborhoodName: '동네명',
    name: '팝업스토어 제목',
    area: 0,
    numOfPeople: 0,
    date: 4,
    price: 100000,
    isLiked: false,
  },
];
