import { ReservationItem } from '@type/reservation';

export const reservationDummy: ReservationItem[] = [
  {
    id: 1,
    status: 'pending',
    imageUrl: 'https://placehold.co/600x400/png',
    brandName: '브랜드 이름',
    cityName: '도시명',
    neighborhoodName: '동네명',
    name: '팝업스토어 제목',
    area: 0,
    capacity: 0,
    date: 31,
    totalPrice: 1550000,
    reservationDate: '0000.0.0',
    reservationoTime: '00:00',
    startDate: '00.00.00',
    endDate: '00.00.00',
  },
  {
    id: 2,
    status: 'pending',
    imageUrl: 'https://placehold.co/600x400/png',
    brandName: '브랜드 이름',
    cityName: '도시명',
    neighborhoodName: '동네명',
    name: '팝업스토어 제목',
    area: 0,
    capacity: 0,
    date: 31,
    totalPrice: 1550000,
    reservationDate: '0000.0.0',
    reservationoTime: '00:00',
    startDate: '00.00.00',
    endDate: '00.00.00',
  },
  {
    id: 3,
    status: 'pending',
    imageUrl: 'https://placehold.co/600x400/png',
    brandName: '브랜드 이름',
    cityName: '도시명',
    neighborhoodName: '동네명',
    name: '팝업스토어 제목',
    area: 0,
    capacity: 0,
    date: 31,
    totalPrice: 1550000,
    reservationDate: '0000.0.0',
    reservationoTime: '00:00',
    startDate: '00.00.00',
    endDate: '00.00.00',
  },
];
